spring:
  datasource:
    # Ở môi trường Prod trong Docker, các service gọi nhau bằng tên container và port nội bộ (3306)
    url: jdbc:mysql://mysql:3306/worklify_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: worklify
    password: worklify_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ĐÃ XÓA RABBITMQ

  jpa:
    hibernate:
      # Validate để đảm bảo an toàn dữ liệu trên Production
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.worklify: INFO
    org.hibernate.SQL: WARN