spring:
  application:
    name: worklify-api

  datasource:
    # Chạy trên IDE gọi vào MySQL Docker qua cổng 3307
    url: jdbc:mysql://localhost:3307/worklify_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: worklify
    password: worklify_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # Để none vì chúng ta đã dùng file init.sql để tạo bảng từ đầu
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # ĐÃ XÓA CẤU HÌNH RABBITMQ VÌ KHÔNG CÒN DÙNG AI NỮA

  security:
    jwt:
      secret: c21hcnRtYXRjaC1zdXBlci1zZWNyZXQta2V5LTIwMjYtbWluaW11bS0yNTYtYml0cyE=
      expiration: 86400000
      refresh-expiration: 604800000

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    com.worklify: DEBUG
    org.hibernate.SQL: DEBUG